"""
yadopt.datamodel - YadOptArgs and its generator.
"""
from __future__ import annotations

# Import standard libraries.
import dataclasses

# For type hinting.
from typing import Any

# Import custom modules.
from .errors import YadOptError

# Declare published functions and variables.
__all__ = ["YadOptArgs", "make_yadoptargs_data"]


class YadOptArgs:
    """
    Base class for parsed command line arguments.
    This class is designed to be dynamically extended with dataclass features based on the parsed arguments.
    """
    def __eq__(self, other: Any) -> bool:
        """
        Equality comparison for YadOptArgs instances.
        """
        if dataclasses.is_dataclass(self) and dataclasses.is_dataclass(other):
            return dataclasses.asdict(self) == dataclasses.asdict(other)
        return NotImplemented

    def __or__(self, other: Any) -> YadOptArgs:
        """
        Merge operation for YadOptArgs instances.
        """
        return merge(self, other)

    def __len__(self) -> int:
        """
        Returns the number of items.
        """
        if dataclasses.is_dataclass(self):
            return len(dataclasses.fields(self))
        raise NotImplementedError


def make_yadoptargs_data(data_dict: dict[str, Any], groups: dict[str, list[str]], base_cls: type) -> Any:
    """
    Dynamically create a YadOptArgs class with the given fields.

    Args:
        data_dict (dict[str, Any])      : [IN] Dictionary of parsed arguments.
        groups    (dict[str, list[str]]): [IN] Dictionary of group information.
        base_cls  (type)                : [IN] Base class for the dynamically created class.

    Returns:
        (Any): An instance of the dynamically created dataclass.
    """
    # Normalize the key names to be valid Python identifiers.
    data_dict_normalized: dict = {name.replace("-", "_").replace(".", "_"): value for name, value in data_dict.items()}

    dynamic_yadopt_args: type = dataclasses.make_dataclass(

        # Basic properties of the dynamically created class.
        cls_name = base_cls.__name__,

        # Set the frozen property based on whether the base class is frozen or if it is YadOptArgs.
        frozen = is_dataclass_frozen(base_cls) or (base_cls is YadOptArgs),

        # Create fields of the dataclass.
        fields = [(name, type(value)) for name, value in data_dict_normalized.items()],

        # Custom methods for the dynamically created class.
        namespace = {
            "_groups_": groups,
        },

        # Set the base class to YadOptArgs to inherit its methods and properties.
        bases = (base_cls, YadOptArgs) if base_cls is not YadOptArgs else (YadOptArgs,),

        # Disable the default __eq__ method generated by dataclasses.
        eq = False,
    )

    # Set the module name of the dynamically created class to "yadopt" for better introspection.
    dynamic_yadopt_args.__module__ = "yadopt"

    return dynamic_yadopt_args(**data_dict_normalized)


def merge(lhs: YadOptArgs, rhs: YadOptArgs) -> YadOptArgs:
    """
    Merge operation for YadOptArgs instances.

    Args:
        lhs (YadOptArgs): [IN] Left-hand side YadOptArgs instance.
        rhs (YadOptArgs): [IN] Right-hand side YadOptArgs instance.

    Returns:
        (YadOptArgs): Merged YadOptArgs instance.
    """
    # The operand must be an instance of YadOptArgs.
    if not isinstance(lhs, YadOptArgs) or not dataclasses.is_dataclass(lhs):
        raise YadOptError.CannotMerge(cls_name=lhs.__class__.__name__)
    if not isinstance(rhs, YadOptArgs) or not dataclasses.is_dataclass(rhs):
        raise YadOptError.CannotMerge(cls_name=rhs.__class__.__name__)

    # Merge the group information by merging the "_groups_" dictionaries of the two instances.
    groups_lhs: dict[str, list[str]] = getattr(lhs, "_groups_")
    groups_rhs: dict[str, list[str]] = getattr(rhs, "_groups_")
    groups_merged: dict[str, list[str]] = {}
    for key, set_group_names in (groups_lhs | groups_rhs).items():
        for value in set_group_names:
            groups_merged.setdefault(key, []).append(value)

    # Merge the two YadOptArgs instances by merging their dictionaries.
    args_dict: dict[str, Any] = dataclasses.asdict(lhs) | dataclasses.asdict(rhs)

    # Returns YadOptArgs instance.
    return make_yadoptargs_data(args_dict, groups_merged, base_cls=YadOptArgs)


def is_dataclass_frozen(obj: object) -> bool:
    """
    Check if the given object is a frozen dataclass.

    Args:
        obj (object): The object to check.

    Returns:
        (bool): True if the object is a frozen dataclass, False otherwise.

    Examples:
        >>> @dataclasses.dataclass(frozen=True)
        ... class FrozenClass:
        ...     x: int
        >>> is_dataclass_frozen(FrozenClass(10))
        True
        >>> @dataclasses.dataclass(frozen=False)
        ... class NonFrozenClass:
        ...     x: int
        >>> is_dataclass_frozen(NonFrozenClass(10))
        False
    """
    # Check if the object is a frozen dataclass.
    if not dataclasses.is_dataclass(obj):
        return False

    try:
        setattr(obj, "__dict__", getattr(obj, "__dict__", None))
    except dataclasses.FrozenInstanceError:
        return True
    except (TypeError, AttributeError):
        return False
    return False


# vim: expandtab tabstop=4 shiftwidth=4 fdm=marker
